In [16]:
import pandas as pd
df=pd.read_csv("E:\movieset.csv")
df.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",12/10/2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",5/19/2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",10/26/2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7/16/2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",3/7/2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [2]:
import os

print(os.getcwd())

C:\Users\ASUS

In [8]:
print(df.shape)

(4803, 20)

In [10]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [11]:
movies=df[
    [
    'title',
    'genres',
    'overview',
    'release_date',
    'vote_average',
    'vote_count',
    'original_language',
    'popularity'
    ]
].copy()

movies.head()

,title,genres,overview,release_date,vote_average,vote_count,original_language,popularity
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...",12/10/2009,7.2,11800,en,150.437577
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...",5/19/2007,6.9,4500,en,139.082615
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him...,10/26/2015,6.3,4466,en,107.376788
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,7/16/2012,7.6,9106,en,112.312950
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...",3/7/2012,6.1,2124,en,43.926995

In [12]:
movies.isnull().sum()

title                0
genres               0
overview             3
release_date         1
vote_average         0
vote_count           0
original_language    0
popularity           0
dtype: int64

In [13]:
movies = movies.dropna(subset=['overview']).copy()

print("Dataset shape:", movies.shape)
print("Missing values:")
print(movies.isnull().sum())

Dataset shape: (4800, 8)
Missing values:
title                0
genres               0
overview             0
release_date         1
vote_average         0
vote_count           0
original_language    0
popularity           0
dtype: int64

In [15]:
movies['genres'].head(5)

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: str

In [17]:
import ast

def get_genres(genre_text):
    genre_list = ast.literal_eval(genre_text)
    return [genre['name'] for genre in genre_list]

movies['genres'] = movies['genres'].apply(get_genres)

movies[['title', 'genres']].head(5)

,title,genres
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]"
2,Spectre,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]"
4,John Carter,"[Action, Adventure, Science Fiction]"

In [18]:
all_genres = sorted(set(
    genre
    for genre_list in movies['genres']
    for genre in genre_list
))

print(all_genres)
print("Total genres:", len(all_genres))

['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
Total genres: 20

In [19]:
print(all_genres)
print("Total genres:", len(all_genres))

['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
Total genres: 20

In [20]:
def recommend_by_genre(genre, n=10):
    recommendations = movies[
        movies['genres'].apply(lambda genres: genre in genres)
    ]

    recommendations = recommendations.sort_values(
        by=['vote_count', 'popularity'],
        ascending=False
    )

    return recommendations[
        ['title', 'genres', 'overview', 'release_date', 'vote_average']
    ].head(n)

In [21]:
recommend_by_genre("Romance")

,title,genres,overview,release_date,vote_average
809,Forrest Gump,"[Comedy, Drama, Romance]",A man with a low IQ has accomplished great thi...,7/6/1994,8.2
25,Titanic,"[Drama, Romance, Thriller]","84 years later, a 101-year-old woman named Ros...",11/18/1997,7.5
2071,Silver Linings Playbook,"[Drama, Comedy, Romance]",After spending eight months in a mental instit...,9/8/2012,6.9
81,Maleficent,"[Fantasy, Adventure, Action, Family, Romance]",The untold story of Disney's most iconic villa...,5/28/2014,7.0
1997,Her,"[Romance, Science Fiction, Drama]","In the not so distant future, Theodore, a lone...",12/18/2013,7.9
49,The Great Gatsby,"[Drama, Romance]",An adaptation of F. Scott Fitzgerald's Long Is...,5/10/2013,7.3
2838,The Fault in Our Stars,"[Romance, Drama]",Despite the tumor-shrinking medical miracle th...,5/16/2014,7.6
2152,Eternal Sunshine of the Spotless Mind,"[Science Fiction, Drama, Romance]","Joel Barish, heartbroken that his girlfriend u...",3/19/2004,7.9
2108,Edward Scissorhands,"[Fantasy, Drama, Romance]",A small suburban town receives a visit from a ...,12/5/1990,7.5
1337,Twilight,"[Adventure, Fantasy, Drama, Romance]",When Bella Swan moves to a small town in the P...,11/20/2008,5.8

In [22]:
recommend_by_genre("Romance", 5)

,title,genres,overview,release_date,vote_average
809,Forrest Gump,"[Comedy, Drama, Romance]",A man with a low IQ has accomplished great thi...,7/6/1994,8.2
25,Titanic,"[Drama, Romance, Thriller]","84 years later, a 101-year-old woman named Ros...",11/18/1997,7.5
2071,Silver Linings Playbook,"[Drama, Comedy, Romance]",After spending eight months in a mental instit...,9/8/2012,6.9
81,Maleficent,"[Fantasy, Adventure, Action, Family, Romance]",The untold story of Disney's most iconic villa...,5/28/2014,7.0
1997,Her,"[Romance, Science Fiction, Drama]","In the not so distant future, Theodore, a lone...",12/18/2013,7.9

In [23]:
movies['overview'] = movies['overview'].fillna('')

movies['overview_clean'] = (
    movies['overview']
    .str.lower()
    .str.strip()
)

movies[['title', 'overview_clean']].head(5)

,title,overview_clean
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,Spectre,a cryptic message from bondâ€™s past sends him...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,"john carter is a war-weary, former military ca..."

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("TF-IDF and cosine similarity are ready!")

TF-IDF and cosine similarity are ready!

In [25]:
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)

tfidf_matrix = tfidf.fit_transform(movies['overview_clean'])

print("Matrix shape:", tfidf_matrix.shape)

Matrix shape: (4800, 5000)

In [26]:
similarity_matrix = cosine_similarity(tfidf_matrix)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (4800, 4800)

In [29]:
def recommend_similar_movies(title, n=10):
    matches = movies[
        movies['title'].str.casefold() == title.casefold()
    ]

    if matches.empty:
        print("Movie not found. Check the title spelling.")
        return

    position = movies.index.get_loc(matches.index[0])

    scores = list(enumerate(similarity_matrix[position]))
    scores = sorted(scores, key=lambda item: item[1], reverse=True)

    scores = [
        item for item in scores if item[0] != position
    ][:n]

    positions = [item[0] for item in scores]

    recommendations = movies.iloc[positions][
        ['title', 'genres', 'overview', 'release_date', 'vote_average']
    ].copy()

    recommendations['similarity_score'] = [
        round(score, 3) for _, score in scores
    ]

    return recommendations

In [30]:
recommend_similar_movies("The Dark Knight")

,title,genres,overview,release_date,vote_average,similarity_score
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,7/16/2012,7.6,0.368
299,Batman Forever,"[Action, Crime, Fantasy]",The Dark Knight of Gotham City confronts a das...,5/31/1995,5.2,0.278
428,Batman Returns,"[Action, Fantasy]","Having defeated the Joker, Batman now faces th...",6/19/1992,6.6,0.277
3854,"Batman: The Dark Knight Returns, Part 2","[Action, Animation]",Batman has stopped the reign of terror that Th...,1/18/2013,7.9,0.259
119,Batman Begins,"[Action, Crime, Drama]","Driven by tragedy, billionaire Bruce Wayne ded...",6/10/2005,7.5,0.193
1181,JFK,"[Drama, Thriller, History]",New Orleans District Attorney Jim Garrison dis...,12/20/1991,7.5,0.165
1359,Batman,"[Fantasy, Action]",The Dark Knight of Gotham City begins his war ...,6/23/1989,7.0,0.165
9,Batman v Superman: Dawn of Justice,"[Action, Adventure, Fantasy]",Fearing the actions of a god-like Super Hero l...,3/23/2016,5.7,0.161
2507,Slow Burn,"[Mystery, Crime, Drama, Thriller]",A district attorney (Ray Liotta) is involved i...,9/12/2005,5.5,0.152
210,Batman & Robin,"[Action, Crime, Fantasy]",Along with crime-fighting partner Robin and ne...,6/20/1997,4.2,0.138

In [31]:
def recommend_by_genre_and_movie(genre, favorite_movie, n=10):
    matches = movies[
        movies['title'].str.casefold()
        == favorite_movie.casefold()
    ]

    if matches.empty:
        print("Favorite movie not found. Check the title spelling.")
        return

    position = movies.index.get_loc(matches.index[0])

    genre_matches = movies['genres'].apply(
        lambda genres: genre in genres
    )

    candidates = movies[genre_matches].copy()
    candidates['similarity_score'] = similarity_matrix[
        position, [movies.index.get_loc(i) for i in candidates.index]
    ]

    candidates = candidates[
        candidates.index != movies.index[position]
    ]

    return candidates.sort_values(
        by=['similarity_score', 'vote_count'],
        ascending=False
    )[
        ['title', 'genres', 'overview', 'release_date',
         'vote_average', 'similarity_score']
    ].head(n)

In [32]:
recommend_by_genre_and_movie(
    "Action",
    "The Dark Knight",
    10
)

,title,genres,overview,release_date,vote_average,similarity_score
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,7/16/2012,7.6,0.368039
299,Batman Forever,"[Action, Crime, Fantasy]",The Dark Knight of Gotham City confronts a das...,5/31/1995,5.2,0.278387
428,Batman Returns,"[Action, Fantasy]","Having defeated the Joker, Batman now faces th...",6/19/1992,6.6,0.276630
3854,"Batman: The Dark Knight Returns, Part 2","[Action, Animation]",Batman has stopped the reign of terror that Th...,1/18/2013,7.9,0.259073
119,Batman Begins,"[Action, Crime, Drama]","Driven by tragedy, billionaire Bruce Wayne ded...",6/10/2005,7.5,0.192692
1359,Batman,"[Fantasy, Action]",The Dark Knight of Gotham City begins his war ...,6/23/1989,7.0,0.164530
9,Batman v Superman: Dawn of Justice,"[Action, Adventure, Fantasy]",Fearing the actions of a god-like Super Hero l...,3/23/2016,5.7,0.161042
210,Batman & Robin,"[Action, Crime, Fantasy]",Along with crime-fighting partner Robin and ne...,6/20/1997,4.2,0.137669
205,Sherlock Holmes: A Game of Shadows,"[Adventure, Action, Crime, Mystery]",There is a new criminal mastermind at large (P...,11/22/2011,7.0,0.127435
4135,Gangster's Paradise: Jerusalema,"[Drama, Action, Crime, Foreign]",This South African movie tracks the rise of a ...,2/11/2008,6.8,0.120093

In [33]:
duplicate_titles = movies[
    movies['title'].duplicated(keep=False)
].sort_values('title')

print("Number of rows with duplicate titles:", len(duplicate_titles))

duplicate_titles[
    ['title', 'release_date', 'original_language']
].head(15)

Number of rows with duplicate titles: 6

                title release_date original_language
1359           Batman    6/23/1989                en
4267           Batman    7/30/1966                en
3647  Out of the Blue     5/1/1980                en
3693  Out of the Blue   10/12/2006                en
972          The Host    3/22/2013                en
2877         The Host    7/27/2006                ko

In [34]:
def find_movie(title, year):
    results = movies[
        (movies['title'].str.casefold() == title.casefold()) &
        (pd.to_datetime(
            movies['release_date'], errors='coerce'
        ).dt.year == year)
    ]

    if results.empty:
        print("No matching movie found.")
    else:
        return results[
            ['title', 'release_date', 'original_language',
             'genres', 'vote_average']
        ]

In [35]:
find_movie("Batman", 1989)

       title release_date original_language             genres  vote_average
1359  Batman    6/23/1989                en  [Fantasy, Action]           7.0

In [36]:
def recommend_by_language(language, n=10):
    results = movies[
        movies['original_language'].str.lower() == language.lower()
    ].copy()

    results = results.sort_values(
        by=['vote_count', 'popularity'],
        ascending=False
    )

    return results[
        ['title', 'original_language', 'genres',
         'release_date', 'vote_average']
    ].head(n)

In [37]:
recommend_by_language("ko", 10)

,title,original_language,genres,release_date,vote_average
1286,Snowpiercer,ko,"[Action, Science Fiction, Drama]",8/1/2013,6.7
3940,Oldboy,ko,"[Drama, Thriller, Mystery, Action]",1/1/2003,8.0
2877,The Host,ko,"[Horror, Drama, Science Fiction]",7/27/2006,6.7
3711,Sympathy for Lady Vengeance,ko,"[Drama, Thriller]",7/29/2005,7.4
3189,The Wailing,ko,"[Horror, Mystery]",5/12/2016,7.2
3136,"The Good, The Bad, The Weird",ko,"[Action, Adventure, Comedy, Western]",7/16/2008,7.1
2806,Tae Guk Gi: The Brotherhood of War,ko,"[Action, Adventure, Drama, History, War]",2/5/2004,7.4
1518,Dragon Wars: D-War,ko,"[Fantasy, Drama, Horror, Action, Thriller, Sci...",2/8/2007,4.0
2521,Tidal Wave,ko,"[Action, Adventure, Drama, Thriller]",6/6/2009,6.5
2784,Operation Chromite,ko,"[History, Drama, War, Action]",7/27/2016,5.8

In [38]:
def recommend_by_rating(min_rating=7.0, n=10):
    results = movies[
        movies['vote_average'] >= min_rating
    ].copy()

    results = results.sort_values(
        by=['vote_average', 'vote_count'],
        ascending=False
    )

    return results[
        ['title', 'genres', 'release_date',
         'vote_average', 'vote_count']
    ].head(n)

In [39]:
recommend_by_rating(7.5, 10)

,title,genres,release_date,vote_average,vote_count
4247,Me You and Five Bucks,"[Romance, Comedy, Drama]",7/7/2015,10.0,2
3519,Stiff Upper Lips,[Comedy],6/12/1998,10.0,1
4045,"Dancer, Texas Pop. 81","[Comedy, Drama, Family]",5/1/1998,10.0,1
4662,Little Big Top,[Comedy],1/1/2006,10.0,1
3992,Sardaarji,[],6/26/2015,9.5,2
2386,One Man's Hero,"[Western, Action, Drama, History]",8/2/1999,9.3,2
1881,The Shawshank Redemption,"[Drama, Crime]",9/23/1994,8.5,8205
2970,There Goes My Baby,"[Drama, Comedy]",9/2/1994,8.5,2
3337,The Godfather,"[Drama, Crime]",3/14/1972,8.4,5893
2796,The Prisoner of Zenda,"[Adventure, Drama, Romance]",9/3/1937,8.4,11

In [40]:
mood_genres = {
    "happy": ["Comedy", "Animation", "Family"],
    "sad": ["Comedy", "Romance", "Family"],
    "romantic": ["Romance"],
    "adventurous": ["Adventure", "Action", "Fantasy"],
    "scared": ["Horror", "Thriller"],
    "curious": ["Mystery", "Science Fiction", "Crime"],
    "inspired": ["Drama", "History"],
    "relaxed": ["Comedy", "Family", "Music"]
}

def recommend_by_mood(mood, n=10):
    mood = mood.lower().strip()

    if mood not in mood_genres:
        print("Mood not found. Available moods:", list(mood_genres))
        return

    selected_genres = mood_genres[mood]

    results = movies[
        movies['genres'].apply(
            lambda genres: any(
                genre in genres for genre in selected_genres
            )
        )
    ].copy()

    results = results.sort_values(
        by=['vote_count', 'popularity'],
        ascending=False
    )

    return results[
        ['title', 'genres', 'overview',
         'release_date', 'vote_average']
    ].head(n)

In [41]:
recommend_by_mood("sad", 10)

,title,genres,overview,release_date,vote_average
788,Deadpool,"[Action, Adventure, Comedy]",Deadpool tells the origin story of former Spec...,2/9/2016,7.4
809,Forrest Gump,"[Comedy, Drama, Romance]",A man with a low IQ has accomplished great thi...,7/6/1994,8.2
25,Titanic,"[Drama, Romance, Thriller]","84 years later, a 101-year-old woman named Ros...",11/18/1997,7.5
197,Harry Potter and the Philosopher's Stone,"[Adventure, Fantasy, Family]",Harry Potter has lived under the stairs at his...,11/16/2001,7.5
66,Up,"[Animation, Comedy, Family, Adventure]",Carl Fredricksen spent his entire life dreamin...,5/13/2009,7.7
298,The Wolf of Wall Street,"[Crime, Drama, Comedy]",A New York stockbroker refuses to cooperate in...,12/25/2013,7.9
77,Inside Out,"[Drama, Comedy, Animation, Family]","Growing up can be a bumpy road, and it's no ex...",6/9/2015,8.0
614,Despicable Me,"[Animation, Family]",Villainous Gru lives up to his reputation as a...,7/8/2010,7.1
57,WALLÂ·E,"[Animation, Family]",WALLÂ·E is the last robot left on an Earth tha...,6/22/2008,7.8
1356,The Hangover,[Comedy],When three friends finally come to after a rau...,6/5/2009,7.2

In [42]:
def show_movies(recommendations):
    if recommendations is None or recommendations.empty:
        print("No movies found.")
        return

    for _, movie in recommendations.iterrows():
        print("=" * 60)
        print("Title:", movie['title'])
        print("Genres:", ", ".join(movie['genres']))
        print("Rating:", movie['vote_average'])
        print("Release date:", movie['release_date'])
        print("Overview:", movie['overview'])
        print()

In [43]:
results = recommend_by_mood("romantic", 5)
show_movies(results)

============================================================
Title: Forrest Gump
Genres: Comedy, Drama, Romance
Rating: 8.2
Release date: 7/6/1994
Overview: A man with a low IQ has accomplished great things in his life and been present during significant historic events - in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him. 'Forrest Gump' is the story of a man who rose above his challenges, and who proved that determination, courage, and love are more important than ability.

============================================================
Title: Titanic
Genres: Drama, Romance, Thriller
Rating: 7.5
Release date: 11/18/1997
Overview: 84 years later, a 101-year-old woman named Rose DeWitt Bukater tells the story to her granddaughter Lizzy Calvert, Brock Lovett, Lewis Bodine, Bobby Buell and Anatoly Mikailavich on the Keldysh about her life set in April 10th 1912, on a ship called Titanic when young Rose boards the departing ship with the upper-class passengers and her mother, Ruth DeWitt Bukater, and her fiancÃ©, Caledon Hockley. Meanwhile, a drifter and artist named Jack Dawson and his best friend Fabrizio De Rossi win third-class tickets to the ship in a game. And she explains the whole story from departure until the death of Titanic on its first and last voyage April 15th, 1912 at 2:20 in the morning.

============================================================
Title: Silver Linings Playbook
Genres: Drama, Comedy, Romance
Rating: 6.9
Release date: 9/8/2012
Overview: After spending eight months in a mental institution, a former teacher moves back in with his parents and tries to reconcile with his ex-wife.

============================================================
Title: Maleficent
Genres: Fantasy, Adventure, Action, Family, Romance
Rating: 7.0
Release date: 5/28/2014
Overview: The untold story of Disney's most iconic villain from the 1959 classic 'Sleeping Beauty'. A beautiful, pure-hearted young woman, Maleficent has an idyllic life growing up in a peaceable forest kingdom, until one day when an invading army threatens the harmony of the land.  Maleficent rises to be the land's fiercest protector, but she ultimately suffers a ruthless betrayal â€“ an act that begins to turn her heart into stone. Bent on revenge, Maleficent faces an epic battle with the invading King's successor and, as a result, places a curse upon his newborn infant Aurora. As the child grows, Maleficent realizes that Aurora holds the key to peace in the kingdom - and to Maleficent's true happiness as well.

============================================================
Title: Her
Genres: Romance, Science Fiction, Drama
Rating: 7.9
Release date: 12/18/2013
Overview: In the not so distant future, Theodore, a lonely writer purchases a newly developed operating system designed to meet the user's every needs. To Theordore's surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.

In [44]:
print("1. Genre recommendations")
display(recommend_by_genre("Comedy", 3))

print("2. Similar-movie recommendations")
display(recommend_similar_movies("The Dark Knight", 3))

print("3. Language recommendations")
display(recommend_by_language("ko", 3))

print("4. Rating recommendations")
display(recommend_by_rating(7.5, 3))

print("5. Mood recommendations")
display(recommend_by_mood("romantic", 3))

1. Genre recommendations

,title,genres,overview,release_date,vote_average
788,Deadpool,"[Action, Adventure, Comedy]",Deadpool tells the origin story of former Spec...,2/9/2016,7.4
809,Forrest Gump,"[Comedy, Drama, Romance]",A man with a low IQ has accomplished great thi...,7/6/1994,8.2
66,Up,"[Animation, Comedy, Family, Adventure]",Carl Fredricksen spent his entire life dreamin...,5/13/2009,7.7

2. Similar-movie recommendations

,title,genres,overview,release_date,vote_average,similarity_score
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,7/16/2012,7.6,0.368
299,Batman Forever,"[Action, Crime, Fantasy]",The Dark Knight of Gotham City confronts a das...,5/31/1995,5.2,0.278
428,Batman Returns,"[Action, Fantasy]","Having defeated the Joker, Batman now faces th...",6/19/1992,6.6,0.277

3. Language recommendations

,title,original_language,genres,release_date,vote_average
1286,Snowpiercer,ko,"[Action, Science Fiction, Drama]",8/1/2013,6.7
3940,Oldboy,ko,"[Drama, Thriller, Mystery, Action]",1/1/2003,8.0
2877,The Host,ko,"[Horror, Drama, Science Fiction]",7/27/2006,6.7

4. Rating recommendations

,title,genres,release_date,vote_average,vote_count
4247,Me You and Five Bucks,"[Romance, Comedy, Drama]",7/7/2015,10.0,2
3519,Stiff Upper Lips,[Comedy],6/12/1998,10.0,1
4045,"Dancer, Texas Pop. 81","[Comedy, Drama, Family]",5/1/1998,10.0,1

5. Mood recommendations

,title,genres,overview,release_date,vote_average
809,Forrest Gump,"[Comedy, Drama, Romance]",A man with a low IQ has accomplished great thi...,7/6/1994,8.2
25,Titanic,"[Drama, Romance, Thriller]","84 years later, a 101-year-old woman named Ros...",11/18/1997,7.5
2071,Silver Linings Playbook,"[Drama, Comedy, Romance]",After spending eight months in a mental instit...,9/8/2012,6.9

In [45]:
movies.to_csv("NextWatch_Cleaned_Movies.csv", index=False)

print("Cleaned movie dataset saved successfully!")

Cleaned movie dataset saved successfully!

In [46]:
import os

print(os.path.abspath("moviedataset.ipynb"))

C:\Users\ASUS\moviedataset.ipynb